(()=>{
'use strict';
const START='1311852361739694080', API='https://api.sleeper.app/v1', FC='https://api.fantasycalc.com/values/current';
const S={league:null,leagueId:START,users:[],rosters:[],players:{},picks:[],tx:[],dyn:new Map(),red:new Map(),teams:[]};
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)], fmt=n=>Math.round(n||0).toLocaleString(), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
async function getJSON(url,ms=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return await r.json()}catch(e){if(e.name==='AbortError')throw Error('request timed out');throw e}finally{clearTimeout(t)}}
async function resolveLeague(id){let leagueId=String(id),league=null,seen=new Set;for(let i=0;i<5;i++){if(seen.has(leagueId))break;seen.add(leagueId);league=await getJSON(`${API}/league/${leagueId}`);const next=league?.next_league_id&&String(league.next_league_id)!=='0'?String(league.next_league_id):null;if(!next)return{league,leagueId};leagueId=next}return{league,leagueId}}
function vmap(rows){const m=new Map;for(const x of rows||[]){const id=x?.player?.sleeperId??x?.sleeperId??x?.player?.sleeper_id;if(!id)continue;m.set(String(id),{v:+(x.value||0),age:+(x?.player?.age||x.age||0)||null,name:x?.player?.name||x.name,pos:x?.player?.position||x.position,team:x?.player?.maybeTeam||x?.player?.team||x.team,pr:x.positionRank??null})}return m}
async function fantasy(dynasty){const u=new URL(FC);u.searchParams.set('isDynasty',dynasty?'true':'false');u.searchParams.set('numQbs','2');u.searchParams.set('numTeams','12');u.searchParams.set('ppr','1');return getJSON(u,10000)}
function info(id){id=String(id);const p=S.players[id]||{},d=S.dyn.get(id)||{},r=S.red.get(id)||{};return{id,name:p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||d.name||r.name||`Player ${id}`,pos:p.position||d.pos||r.pos||'',team:p.team||d.team||r.team||'FA',age:d.age||p.age||null,dv:d.v||0,rv:r.v||0,pr:d.pr||null}}
function pickVal(y,r){const base={1:4200,2:1900,3:800,4:300,5:120}[+r]||100,now=+(S.league?.season||2026);return base*Math.pow(.9,Math.max(0,+y-now))}
function owned(rid){const now=+(S.league?.season||2026),rounds=+(S.league?.settings?.draft_rounds||4),out=[];for(let y=now+1;y<=now+3;y++)for(let r=1;r<=rounds;r++){const mv=S.picks.find(x=>+x.season===y&&+x.round===r&&+x.roster_id===rid),owner=mv?+mv.owner_id:rid;if(owner===rid)out.push({y,r,from:rid})}for(const p of S.picks){const y=+p.season,r=+p.round;if(+p.owner_id===rid&&+p.roster_id!==rid&&y>=now+1&&y<=now+3&&!out.some(x=>x.y===y&&x.r===r&&x.from===+p.roster_id))out.push({y,r,from:+p.roster_id})}return out.sort((a,b)=>a.y-b.y||a.r-b.r)}
function bestLine(ps,key){const slots=S.league?.roster_positions||['QB','RB','RB','WR','WR','TE','FLEX','SUPER_FLEX'],used=new Set;let total=0;const take=eligible=>{let bi=-1,b=null;ps.forEach((p,i)=>{if(used.has(i)||!eligible.includes(p.pos))return;if(!b||(p[key]||0)>(b[key]||0)){b=p;bi=i}});if(b){used.add(bi);total+=b[key]||0}};for(const s of slots){if(s==='QB')take(['QB']);else if(s==='RB')take(['RB']);else if(s==='WR')take(['WR']);else if(s==='TE')take(['TE']);else if(s==='FLEX')take(['RB','WR','TE']);else if(s.includes('SUPER'))take(['QB','RB','WR','TE'])}return total}
function norm(a){if(!a.length)return[];const lo=Math.min(...a),hi=Math.max(...a);return a.map(v=>hi===lo?50:(v-lo)/(hi-lo)*100)}
function ageWt(ps){const a=ps.filter(p=>p.age&&p.dv>0).sort((x,y)=>y.dv-x.dv).slice(0,10),den=a.reduce((s,p)=>s+p.dv,0);return den?a.reduce((s,p)=>s+p.age*p.dv,0)/den:null}
function posValue(ps,pos){return ps.filter(p=>p.pos===pos).reduce((s,p)=>s+p.dv,0)}
function coreValue(ps,pos){const w={QB:[1,.9,.32],RB:[1,.82,.52,.25],WR:[1,.9,.78,.6,.35],TE:[1,.45]}[pos];return ps.filter(p=>p.pos===pos).sort((a,b)=>b.dv-a.dv).slice(0,w.length).reduce((s,p,i)=>s+p.dv*w[i],0)}
function buildTeams(){S.teams=S.rosters.map(r=>{const u=S.users.find(x=>x.user_id===r.owner_id)||{},ps=(r.players||[]).map(info).sort((a,b)=>b.dv-a.dv),op=owned(+r.roster_id),pc=op.reduce((s,p)=>s+pickVal(p.y,p.r),0),dr=ps.slice(0,16).reduce((s,p,i)=>s+p.dv*(i<10?1:.45),0),cr=bestLine(ps,'rv')||bestLine(ps,'dv'),pos={},core={};for(const k of ['QB','RB','WR','TE']){pos[k]=posValue(ps,k);core[k]=coreValue(ps,k)}return{id:+r.roster_id,name:u.metadata?.team_name||u.display_name||`Roster ${r.roster_id}`,owner:u.display_name||'',ps,op,pc,dr,cr,pos,core,age:ageWt(ps)}});const cn=norm(S.teams.map(t=>t.cr)),dn=norm(S.teams.map(t=>t.dr)),pn=norm(S.teams.map(t=>t.pc));S.teams.forEach((t,i)=>t.power=.45*cn[i]+.4*dn[i]+.15*pn[i]);S.teams.sort((a,b)=>b.power-a.power).forEach((t,i)=>t.rank=i+1);for(const k of ['QB','RB','WR','TE']){[...S.teams].sort((a,b)=>b.pos[k]-a.pos[k]).forEach((t,i)=>t[k+'r']=i+1);[...S.teams].sort((a,b)=>b.core[k]-a.core[k]).forEach((t,i)=>t[k+'c']=i+1)}[...S.teams].sort((a,b)=>b.cr-a.cr).forEach((t,i)=>t.cont=i+1);[...S.teams].sort((a,b)=>b.dr-a.dr).forEach((t,i)=>t.dynr=i+1);[...S.teams].sort((a,b)=>b.pc-a.pc).forEach((t,i)=>t.pickr=i+1)}
function mode(t){if(t.cont<=4&&t.dynr<=7)return['Contender','good'];if(t.cont>=8&&t.pickr<=5)return['Rebuilder','warn'];if(t.cont<=6||t.dynr<=6)return['In the Mix','good'];return['Retooling','warn']}
function bars(t){return['QB','RB','WR','TE'].map(k=>`<div class="posrow"><b>${k}</b><div class="bar"><i style="width:${(13-t[k+'r'])/12*100}%"></i></div><span>#${t[k+'r']}</span></div>`).join('')}
function renderPower(){const a=S.teams[0],win=[...S.teams].sort((x,y)=>y.cr-x.cr)[0],picks=[...S.teams].sort((x,y)=>y.pc-x.pc)[0];$('#power').innerHTML=`<div class="hero"><div class="card"><div class="eyebrow">#1 Franchise</div><div class="big">${esc(a.name)}</div><div class="muted">Power ${a.power.toFixed(1)} / 100</div></div><div class="card"><div class="eyebrow">Best Win-Now</div><div class="big">${esc(win.name)}</div><div class="muted">Optimal starting-lineup value</div></div><div class="card"><div class="eyebrow">Draft Capital King</div><div class="big">${esc(picks.name)}</div><div class="muted">#1 future-pick inventory</div></div></div><div class="section"><div class="sectionHead"><div><h2>League Power Rankings</h2><p>45% contender strength • 40% dynasty core • 15% future draft capital</p></div></div><div class="panel"><table><thead><tr><th>#</th><th>Team</th><th>Power</th><th>Win Now</th><th>Dynasty</th><th>Picks</th><th>Mode</th></tr></thead><tbody>${S.teams.map(t=>{const m=mode(t);return`<tr data-team="${t.id}"><td class="rank">#${t.rank}</td><td><b>${esc(t.name)}</b><br><small class="muted">${esc(t.owner)}</small></td><td><div class="scorebar"><b>${t.power.toFixed(1)}</b><div class="bar"><i style="width:${t.power}%"></i></div></div></td><td>#${t.cont}</td><td>#${t.dynr}</td><td>#${t.pickr}</td><td><span class="badge ${m[1]}">${m[0]}</span></td></tr>`}).join('')}</tbody></table></div></div>`;bindTeams('#power')}
function renderTeams(){$('#teams').innerHTML=`<div class="sectionHead"><div><h2>Team War Rooms</h2><p>Click any franchise for roster, positional ranks and future picks.</p></div></div><div class="grid">${S.teams.map(t=>{const m=mode(t);return`<article class="team" data-team="${t.id}"><div class="line"><div><b>${esc(t.name)}</b><div class="muted" style="font-size:10px">Power #${t.rank}</div></div><span class="badge ${m[1]}">${m[0]}</span></div><div class="mini"><div><b>#${t.cont}</b><small>WIN NOW</small></div><div><b>#${t.dynr}</b><small>DYNASTY</small></div><div><b>#${t.pickr}</b><small>PICKS</small></div></div><div class="posbars">${bars(t)}</div></article>`}).join('')}</div>`;bindTeams('#teams')}
function qbs(t){return t.ps.filter(p=>p.pos==='QB'&&p.dv>=1200).length}
function need(t,k){let s=t[k+'c']||12;if(k==='QB'){const n=qbs(t);if(n<2)s+=8;else if(n===2)s+=2}if(k==='TE')s-=1;return s}
function needs(t){return['QB','RB','WR','TE'].map(k=>({k,s:need(t,k)})).sort((a,b)=>b.s-a.s)}
function tradeable(t,k){const p=t.ps.filter(x=>x.pos===k&&x.dv>=900).sort((a,b)=>b.dv-a.dv);if(k==='QB')return qbs(t)>=3?p.slice(2,4):[];if(k==='WR')return p.slice(mode(t)[0]==='Contender'?3:2,6);if(k==='RB')return p.slice(mode(t)[0]==='Contender'?2:1,5);return p.slice(1,4)}
function pickAsset(p){return{type:'pick',y:p.y,r:p.r,from:p.from,v:pickVal(p.y,p.r)}}function playerAsset(p){return{type:'player',p,v:p.dv}}
function pickBundle(t,target){if(target<300)return[];const pool=t.op.map(pickAsset).sort((a,b)=>a.v-b.v),c=[];for(const x of pool)c.push([x]);for(let i=0;i<pool.length;i++)for(let j=i+1;j<pool.length;j++)c.push([pool[i],pool[j]]);let best=[],e=1e9;for(const b of c){if(target<1800&&b.some(x=>x.r===1))continue;const v=b.reduce((s,x)=>s+x.v,0),er=Math.abs(v-target);if(er<e&&v<target*1.45+250){best=b;e=er}}return best}
function pkgGap(a,b){const av=a.reduce((s,x)=>s+x.v,0),bv=b.reduce((s,x)=>s+x.v,0);return{av,bv,g:Math.abs(av-bv)/Math.max(av,bv,1)}}
function suggestions(){const out=[];for(let i=0;i<S.teams.length;i++)for(let j=i+1;j<S.teams.length;j++){const A=S.teams[i],B=S.teams[j];for(const an of needs(A).slice(0,2))for(const bn of needs(B).slice(0,2)){if(an.k===bn.k)continue;if((B[an.k+'c']||12)>6||(A[bn.k+'c']||12)>6)continue;for(const pa of tradeable(A,bn.k))for(const pb of tradeable(B,an.k)){let ag=[playerAsset(pb)],bg=[playerAsset(pa)],g=pkgGap(ag,bg);if(g.g>.1){if(g.av<g.bv)ag.push(...pickBundle(B,g.bv-g.av));else bg.push(...pickBundle(A,g.av-g.bv));g=pkgGap(ag,bg)}if(g.g>.18)continue;let score=an.s+bn.s-g.g*18;if(pb.pos==='QB'&&qbs(A)<2)score+=5;if(pa.pos==='QB'&&qbs(B)<2)score+=5;if(score>=11)out.push({A,B,ag,bg,g,score,why:`${A.name} addresses ${pb.pos} (core rank #${A[pb.pos+'c']}) while ${B.name} addresses ${pa.pos} (core rank #${B[pa.pos+'c']}).${pb.pos==='QB'||pa.pos==='QB'?' The QB side is being treated with Superflex scarcity; a team’s top two viable QBs are protected.':''}`})}}}return out.sort((a,b)=>b.score-a.score||a.g.g-b.g.g).slice(0,8)}
function asset(a){return a.type==='player'?`<div class="asset"><span>${esc(a.p.name)} <small>${a.p.pos}</small></span><small>${fmt(a.v)}</small></div>`:`<div class="asset"><span>${a.y} R${a.r}${a.from?` <small>from #${a.from}</small>`:''}</span><small>${fmt(a.v)}</small></div>`}
function renderIdeas(){const x=suggestions();$('#ideas').innerHTML=`<div class="sectionHead"><div><h2>Trades That Should Be Made</h2><p>Stricter 12-team Superflex logic: QB scarcity, positional surplus, needs and current market value.</p></div><span class="badge good">2-QB / SF aware</span></div>${x.length?`<div class="twocol">${x.map(s=>`<article class="trade"><div class="line"><b>${esc(s.A.name)} × ${esc(s.B.name)}</b><span class="badge">Fit ${Math.round(s.score)}</span></div><div class="tradeSides"><div class="sidebox"><b>${esc(s.A.name)} gets</b>${s.ag.map(asset).join('')}<div><b>${fmt(s.g.av)}</b></div></div><div class="arrow">⇄</div><div class="sidebox"><b>${esc(s.B.name)} gets</b>${s.bg.map(asset).join('')}<div><b>${fmt(s.g.bv)}</b></div></div></div><div class="why"><b>Why:</b> ${esc(s.why)} Market-value gap: ${Math.round(s.g.g*100)}%.</div></article>`).join('')}</div>`:`<div class="card">No trade cleared the stricter filters right now. That is intentional — the page will not invent bad deals just to fill space.</div>`}`}
function rosterName(id){return S.teams.find(t=>t.id===+id)?.name||`Roster ${id}`}
function sides(tr){const ids=[...new Set(tr.roster_ids||[])],m=new Map(ids.map(id=>[+id,{players:[],picks:[],faab:0}]));for(const [pid,rid] of Object.entries(tr.adds||{})){if(!m.has(+rid))m.set(+rid,{players:[],picks:[],faab:0});m.get(+rid).players.push(info(pid))}for(const p of tr.draft_picks||[]){if(!m.has(+p.owner_id))m.set(+p.owner_id,{players:[],picks:[],faab:0});m.get(+p.owner_id).picks.push(p)}for(const w of tr.waiver_budget||[]){const r=+(w.receiver||0);if(r){if(!m.has(r))m.set(r,{players:[],picks:[],faab:0});m.get(r).faab+=+w.amount||0}}return[...m.entries()]}
function sideVal(s){return s.players.reduce((v,p)=>v+p.dv,0)+s.picks.reduce((v,p)=>v+pickVal(p.season,p.round),0)}
function renderTrades(){const seen=new Set,tx=S.tx.filter(t=>t.type==='trade'&&!seen.has(t.transaction_id)&&seen.add(t.transaction_id)).sort((a,b)=>b.created-a.created).slice(0,30);$('#trades').innerHTML=`<div class="sectionHead"><div><h2>Trade Center / Fleece Meter</h2><p>Full trade details. Hindsight values use today’s Superflex market.</p></div></div>${tx.length?`<div class="twocol">${tx.map(t=>{const ss=sides(t),vals=ss.map(([id,s])=>({id,s,v:sideVal(s)}));if(vals.length<2)return'';const two=vals.length===2,g=two?Math.abs(vals[0].v-vals[1].v)/Math.max(vals[0].v,vals[1].v,1):0,pct=two?clamp(vals[0].v/Math.max(vals[0].v+vals[1].v,1)*100,3,97):50,ver=!two?'MULTI-TEAM':g<.1?'EVEN':g<.22?'EDGE':'FLEECE ALERT';return`<article class="trade"><div class="line"><small class="muted">${new Date(t.created).toLocaleDateString()}</small><span class="badge ${g>=.22?'bad':g>=.1?'warn':'good'}">${ver}</span></div><div class="details">${vals.map(x=>`<div class="detail"><h3>${esc(rosterName(x.id))} RECEIVED</h3>${x.s.players.map(p=>`<div class="asset"><span>${esc(p.name)} <small>${p.pos}</small></span><small>${fmt(p.dv)}</small></div>`).join('')}${x.s.picks.map(p=>`<div class="asset"><span>${p.season} R${p.round}</span><small>${fmt(pickVal(p.season,p.round))}</small></div>`).join('')}${x.s.faab?`<div class="asset"><span>FAAB</span><small>$${fmt(x.s.faab)}</small></div>`:''}<div style="margin-top:8px"><b>Total today: ${fmt(x.v)}</b></div></div>`).join('')}</div>${two?`<div class="meter"><i class="dot" style="left:${pct}%"></i></div><div class="muted" style="font-size:10px;text-align:center">Current value gap ${Math.round(g*100)}%</div>`:''}</article>`}).join('')}</div>`:`<div class="card">Trade history is still loading, or no trades were returned for the current league.</div>`}`}
function renderAwards(){const by=f=>[...S.teams].sort(f)[0],list=[['👑','Dynasty Alpha',S.teams[0],'#1 overall franchise'],['🔥','Win-Now Maniac',by((a,b)=>b.cr-a.cr),'Best current starting lineup'],['🧾','Draft Capital Hoarder',by((a,b)=>b.pc-a.pc),'Most future pick value'],['🚀','QB Factory',by((a,b)=>b.pos.QB-a.pos.QB),'Best QB room'],['🐎','RB Stable',by((a,b)=>b.pos.RB-a.pos.RB),'Best RB room'],['🎯','WR Arms Dealer',by((a,b)=>b.pos.WR-a.pos.WR),'Best WR room'],['🧱','TE University',by((a,b)=>b.pos.TE-a.pos.TE),'Best TE room'],['🍼','Young Core',by((a,b)=>(a.age||99)-(b.age||99)),'Youngest value-weighted core']];$('#awards').innerHTML=`<div class="sectionHead"><div><h2>Awards Center</h2><p>Live awards from the current league snapshot.</p></div></div><div class="awardGrid">${list.map(x=>`<article class="award"><div class="awardIcon">${x[0]}</div><b>${x[1]}</b><div class="winner">${esc(x[2]?.name||'—')}</div><small class="muted">${x[3]}</small></article>`).join('')}</div>`}
function bindTeams(root){$$(`${root} [data-team]`).forEach(x=>x.onclick=()=>openTeam(+x.dataset.team))}
function openTeam(id){const t=S.teams.find(x=>x.id===id);if(!t)return;const best=['QB','RB','WR','TE'].sort((a,b)=>t[a+'r']-t[b+'r'])[0],worst=['QB','RB','WR','TE'].sort((a,b)=>t[b+'r']-t[a+'r'])[0];$('#modalBody').innerHTML=`<div class="eyebrow">Team War Room</div><h1>${esc(t.name)}</h1><p>Power #${t.rank} • Win-now #${t.cont} • Dynasty #${t.dynr} • Picks #${t.pickr}</p><div class="hero"><div class="card"><div class="eyebrow">Best Unit</div><div class="big">${best} #${t[best+'r']}</div></div><div class="card"><div class="eyebrow">Biggest Need</div><div class="big">${worst} #${t[worst+'r']}</div></div><div class="card"><div class="eyebrow">Future Picks</div><div class="big">${t.op.length}</div></div></div><div class="rosterGrid">${['QB','RB','WR','TE'].map(k=>`<div class="rosterBox"><b>${k} • League #${t[k+'r']}</b>${t.ps.filter(p=>p.pos===k).slice(0,8).map(p=>`<div class="prow"><span>${esc(p.name)}<br><small class="muted">${esc(p.team)}${p.age?' • '+p.age:''}</small></span><b>${fmt(p.dv)}</b></div>`).join('')}</div>`).join('')}</div><div class="section"><h2>Future Pick Chest</h2><p>${t.op.map(p=>`<span class="badge">${p.y} R${p.r}${p.from!==t.id?' from #'+p.from:''}</span>`).join(' ')||'No tracked future picks'}</p></div>`;$('#modal').classList.add('on')}
function renderAll(){renderPower();renderTeams();renderIdeas();renderTrades();renderAwards()}
async function loadTx(){const calls=[];for(let w=0;w<=18;w++)calls.push(getJSON(`${API}/league/${S.leagueId}/transactions/${w}`,7000).catch(()=>[]));S.tx=(await Promise.all(calls)).flat();renderTrades()}
async function load(){const notice=$('#notice'),status=$('#status');try{const r=await resolveLeague(START);S.league=r.league;S.leagueId=r.leagueId;$('#leagueIdLabel').textContent=S.leagueId;notice.textContent=`Found ${S.league.name||'league'} (${S.league.season||'current'}). Loading rosters…`;const all=await Promise.allSettled([getJSON(`${API}/league/${S.leagueId}/users`),getJSON(`${API}/league/${S.leagueId}/rosters`),getJSON(`${API}/players/nfl?active=true`,15000),getJSON(`${API}/league/${S.leagueId}/traded_picks`),fantasy(true),fantasy(false)]);if(all[0].status!=='fulfilled')throw Error(`users endpoint failed: ${all[0].reason?.message||all[0].reason}`);if(all[1].status!=='fulfilled')throw Error(`rosters endpoint failed: ${all[1].reason?.message||all[1].reason}`);S.users=all[0].value||[];S.rosters=all[1].value||[];if(!S.rosters.length)throw Error(`Sleeper returned zero rosters for league ${S.leagueId}`);S.players=all[2].status==='fulfilled'?all[2].value:{};S.picks=all[3].status==='fulfilled'?all[3].value:[];S.dyn=vmap(all[4].status==='fulfilled'?all[4].value:[]);S.red=vmap(all[5].status==='fulfilled'?all[5].value:[]);buildTeams();renderAll();const missing=[];if(all[2].status!=='fulfilled')missing.push('player metadata');if(all[3].status!=='fulfilled')missing.push('traded picks');if(all[4].status!=='fulfilled')missing.push('dynasty values');if(all[5].status!=='fulfilled')missing.push('redraft values');status.textContent=`Live • ${S.league.season||'current'}${missing.length?' • partial':''}`;status.className='status good';notice.textContent=missing.length?`Core league loaded. Temporary fallback for: ${missing.join(', ')}.`:'League loaded successfully. Trade history is loading in the background.';notice.className=`notice ${missing.length?'warn':'good'}`;loadTx().then(()=>{if(!missing.length)notice.textContent='League and trade history loaded successfully.'}).catch(()=>{})}catch(e){console.error(e);status.textContent='Sync failed';status.className='status';notice.className='notice bad';notice.innerHTML=`<b>Core Sleeper sync failed.</b> ${esc(e.message)}<br><small>The site itself is deployed. This message identifies the data endpoint preventing the dashboard from loading.</small>`}}
const names={power:['DAWG DYNASTY','League Power Rankings'],teams:['FRANCHISE INTELLIGENCE','Team War Rooms'],ideas:['TRADE LAB','Trades That Should Be Made'],trades:['LEAGUE TRANSACTIONS','Trade Center / Fleece Meter'],awards:['BRAGGING RIGHTS','Awards Center']};$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.toggle('on',x===b));$$('.page').forEach(x=>x.classList.toggle('on',x.id===b.dataset.page));$('#eyebrow').textContent=names[b.dataset.page][0];$('#title').textContent=names[b.dataset.page][1]});$$('[data-close]').forEach(x=>x.onclick=()=>$('#modal').classList.remove('on'));document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal').classList.remove('on')});load();
})();